# Site settings
title: "P=NP CTF Team"
baseurl: ""
url: "https://PequalsNP-team.github.io"
bloburl: "https://github.com/PequalsNP-team/pequalsnp-team.github.io/blob/master"

github: PequalsNP-team
twitter: PequalsNP_team
ctftime: https://ctftime.org/team/16879/
disqus: pequalsnp
#google_analytics: UA-80085-YOUR-ID

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Authors
authors:
  thezero:
    url: https://twitter.com/Th3Zer0
  phosphore:
    url: https://twitter.com/lorenzostella

teamname: PequalsNP
