# Site settings
title: "P=NP CTF Team"
baseurl: ""
url: "https://PequalsNP-team.github.io"

github: PequalsNP-team
twitter: PequalsNP_team
ctftime: https://ctftime.org/team/16879/
#disqus: disqus-id
#google_analytics: UA-80085-YOUR-ID

# Build settings
markdown: kramdown
permalink: /:categories/:title

# Authors
authors:
  thezero:
    url: https://twitter.com/Th3Zer0
  phospore:
    url: https://twitter.com/lorenzostella

teamname: PequalsNP
